In [17]:
from pandas_datareader import data as pdr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from dateutil.relativedelta import relativedelta
import quantstats as qs
import warnings
import yfinance as yf
import numpy as np
from bcb import sgs
yf.pdr_override()
warnings.filterwarnings('ignore')

# Como funciona a lógica do programa?

* Pegar composição do Ibovespa desde 2015. (Definir universo investível)
* Criar a lista de códigos de negociação de todas as empresas que passaram no Ibovespa desde 2015.
* Puxar as cotações dessa lista de códigos de negociação. 
* Tratar os dados de cotação: Lidar com dados faltantes, mudar para a frequência mensal e correção/extração das datas. 
* Calcular retornos mensais e 6 meses (retorno da carteira e indicador momento 6 meses).
* Tratar dados de retorno e preço para um formato mais amigável. 
* Calcular retornos do modelo.
* Puxar dados do Ibovespa.
* Tretar os dados e calcular retorno mensal do Ibovespa.
* Visualizar retornos e estatística mensal do modelo e do Ibovespa.
* Calcular retorno ano a ano.
* Calcular retorno acumulado.
* Visualizar retorno acumulado.

In [18]:
tickers = pd.read_excel("composicao_ibov.xlsx")

tickers

,2015-12-31,2016-01-31,2016-02-29,2016-03-31,2016-04-30,2016-05-31,2016-06-30,2016-07-31,2016-08-31,2016-09-30,...,2022-03-31,2022-04-30,2022-05-31,2022-06-30,2022-07-31,2022-08-31,2022-09-30,2022-10-31,2022-11-30,2023-01-31
0,ABEV3,ABEV3,ITUB4,ITUB4,ITUB4,ITUB4,ITUB4,ITUB4,ITUB4,ITUB4,...,VALE3,VALE3,VALE3,VALE3,VALE3,RRRP3,RRRP3,RRRP3,RRRP3,RRRP3
1,AMER3,BBAS3,ABEV3,BBDC4,BBDC4,ABEV3,ABEV3,ABEV3,BBDC4,ABEV3,...,PETR4,PETR4,PETR4,PETR4,PETR4,ALPA4,ALPA4,ALPA4,ALPA4,ALPA4
2,AURE3,BBDC3,BBDC4,ABEV3,ABEV3,BBDC4,BBDC4,BBDC4,ABEV3,BBDC4,...,ITUB4,ITUB4,ITUB4,ITUB4,ITUB4,ABEV3,ABEV3,ABEV3,ABEV3,ABEV3
3,B3SA3,BBDC4,BRFS3,PETR4,PETR4,BRFS3,PETR4,PETR4,PETR4,PETR4,...,BBDC4,BBDC4,BBDC4,BBDC4,PETR3,AMER3,AMER3,AMER3,AMER3,AMER3
4,B3SA3,BBSE3,CIEL3,BRFS3,PETR3,PETR4,BRFS3,BRFS3,BRFS3,BRFS3,...,B3SA3,PETR3,PETR3,PETR3,BBDC4,ARZZ3,ARZZ3,ARZZ3,ARZZ3,ARZZ3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,JHSF3,JHSF3,GOLL4,GOLL4,GOLL4,VALE3,VALE3,VALE3,VALE3,WEGE3
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,EZTC3,EZTC3,JHSF3,EZTC3,CASH3,VIIA3,VIIA3,VIIA3,VIIA3,YDUQ3
89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CASH3,CASH3,EZTC3,CASH3,POSI3,VBBR3,VBBR3,VBBR3,VBBR3,NaN
90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,POSI3,POSI3,CASH3,POSI3,NaN,WEGE3,WEGE3,WEGE3,WEGE3,NaN
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,POSI3,NaN,NaN,YDUQ3,YDUQ3,YDUQ3,YDUQ3,NaN

In [19]:
#pegando lista de tickers

intervalo_tempo = tickers.columns

lista_tickers = []

for mes in intervalo_tempo:

    tickers_no_ano = tickers[mes]

    tickers_no_ano = tickers_no_ano.dropna()

    tickers_no_ano = tickers_no_ano + ".SA"

    lista_tickers.append(tickers_no_ano)


lista_tickers_finais = pd.concat(lista_tickers)

lista_tickers_finais = lista_tickers_finais.drop_duplicates()

lista_tickers_finais = list(lista_tickers_finais)

lista_tickers_finais

intervalo_tempo

DatetimeIndex(['2015-12-31', '2016-01-31', '2016-02-29', '2016-03-31',
               '2016-04-30', '2016-05-31', '2016-06-30', '2016-07-31',
               '2016-08-31', '2016-09-30', '2016-10-31', '2016-11-30',
               '2016-12-31', '2017-01-31', '2017-02-28', '2017-03-31',
               '2017-04-30', '2017-05-31', '2017-06-30', '2017-07-31',
               '2017-08-31', '2017-09-30', '2017-10-31', '2017-11-30',
               '2017-12-31', '2018-01-31', '2018-02-28', '2018-03-31',
               '2018-04-30', '2018-05-31', '2018-06-30', '2018-07-31',
               '2018-08-31', '2018-09-30', '2018-10-31', '2018-11-30',
               '2018-12-31', '2019-01-31', '2019-02-28', '2019-03-31',
               '2019-04-30', '2019-05-31', '2019-06-30', '2019-07-31',
               '2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30',
               '2019-12-31', '2020-01-31', '2020-02-29', '2020-03-31',
               '2020-04-30', '2020-05-31', '2020-06-30', '2020-07-31',
               '2020-08-31', '2020-09-30', '2020-10-31', '2020-11-30',
               '2020-12-31', '2021-01-31', '2021-02-28', '2021-03-31',
               '2021-04-30', '2021-05-31', '2021-06-30', '2021-07-31',
               '2021-08-31', '2021-09-30', '2021-10-31', '2021-11-30',
               '2021-12-31', '2022-01-31', '2022-02-28', '2022-03-31',
               '2022-04-30', '2022-05-31', '2022-06-30', '2022-07-31',
               '2022-08-31', '2022-09-30', '2022-10-31', '2022-11-30',
               '2023-01-31'],
              dtype='datetime64[ns]', freq=None)

In [20]:
#puxando dados de cotação ajustada

dados_cotacoes = pdr.get_data_yahoo(lista_tickers_finais, start="2015-06-30", end= datetime.now())['Adj Close']
dados_cotacoes

[*********************100%***********************]  107 of 107 completed

5 Failed downloads:
- LCAM3.SA: No data found for this date range, symbol may be delisted
- BIDI11.SA: No data found for this date range, symbol may be delisted
- HGTX3.SA: No data found for this date range, symbol may be delisted
- BIDI4.SA: No data found for this date range, symbol may be delisted
- JPSA3.SA: No data found for this date range, symbol may be delisted

,ABEV3.SA,ALPA4.SA,AMER3.SA,ARZZ3.SA,ASAI3.SA,AURE3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,...,UGPA3.SA,USIM5.SA,VALE3.SA,VALE5.SA,VBBR3.SA,VIIA3.SA,VIVT3.SA,VVAR11.SA,WEGE3.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2015-06-30,14.668835,5.577976,19.304613,19.890100,NaN,NaN,NaN,2.914593,16.064671,9.204789,...,29.088478,3.501015,11.896464,14.912727,NaN,6.839885,21.685192,11.133475,6.445274,13.737409
2015-07-01,14.776976,5.665764,18.623274,19.898386,NaN,NaN,NaN,2.894611,15.859564,9.145572,...,28.809885,3.475523,11.779387,14.759581,NaN,6.839885,21.480064,11.222940,6.604626,13.546081
2015-07-02,14.707461,5.631999,18.831461,20.088923,NaN,NaN,NaN,2.884622,15.813248,9.151255,...,29.154808,3.492518,11.753369,14.797868,NaN,6.839885,22.007542,11.073833,6.635139,13.622610
2015-07-03,14.792425,5.638752,18.594885,19.964663,NaN,NaN,NaN,2.857149,15.661069,9.177588,...,28.951395,3.424537,11.499700,NaN,NaN,7.655103,22.007542,NaN,6.723293,13.530773
2015-07-06,14.846498,5.604986,19.683134,19.964663,NaN,NaN,NaN,2.882125,15.780171,8.999825,...,29.185764,3.552001,11.480186,14.328855,NaN,7.655103,21.984100,10.934664,6.716510,13.431284
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-10,12.860000,9.580000,1.100000,77.419998,18.629999,14.97,8.81,11.800000,40.369999,11.590000,...,12.980000,7.340000,86.800003,NaN,15.40,2.050000,39.080002,NaN,38.599998,8.540000
2023-02-13,13.130000,9.850000,1.130000,80.099998,18.670000,15.06,8.43,11.920000,40.599998,11.930000,...,13.050000,7.300000,86.709999,NaN,15.74,2.160000,39.279999,NaN,38.580002,8.580000
2023-02-14,13.000000,9.700000,1.110000,77.519997,18.450001,14.96,8.00,11.440000,41.549999,11.900000,...,12.670000,7.120000,87.099998,NaN,15.29,2.150000,39.529999,NaN,38.360001,8.030000
2023-02-15,13.230000,10.040000,1.130000,78.290001,19.219999,15.01,8.41,11.590000,41.930000,12.130000,...,13.110000,7.240000,89.000000,NaN,15.61,2.270000,39.669998,NaN,38.880001,8.360000
2023-02-16,13.080000,10.020000,1.220000,78.730003,19.010000,15.18,8.03,11.370000,42.400002,12.220000,...,12.890000,7.300000,89.190002,NaN,15.58,2.290000,40.480000,NaN,38.779999,8.380000

In [21]:
#resample pra mensal
dados_cotacoes.index = pd.to_datetime(dados_cotacoes.index)

ultima_linha = dados_cotacoes.iloc[-1:]
dados_cotacoes_mensais = dados_cotacoes.resample("M").last()

dados_cotacoes_mensais

,ABEV3.SA,ALPA4.SA,AMER3.SA,ARZZ3.SA,ASAI3.SA,AURE3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,...,UGPA3.SA,USIM5.SA,VALE3.SA,VALE5.SA,VBBR3.SA,VIIA3.SA,VIVT3.SA,VVAR11.SA,WEGE3.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2015-06-30,14.668835,5.577976,19.304613,19.890100,NaN,NaN,NaN,2.914593,16.064671,9.204789,...,29.088478,3.501015,11.896464,14.912727,NaN,6.839885,21.685192,11.133475,6.445274,13.737409
2015-07-31,15.039612,5.267336,17.118650,17.744524,NaN,NaN,NaN,2.612393,14.589215,9.105167,...,31.078415,3.339560,11.623284,14.022558,NaN,7.655103,22.663952,8.598622,6.371393,10.890436
2015-08-31,14.746079,5.139030,14.762350,18.220686,NaN,NaN,NaN,2.729601,11.887418,8.290726,...,28.220438,2.532288,11.655804,13.543973,NaN,7.655103,20.284359,6.769551,5.703947,9.543482
2015-09-30,15.116618,4.578724,14.062085,16.571829,NaN,NaN,NaN,2.805563,10.301101,7.785673,...,29.701042,2.846699,10.784221,12.749521,NaN,2.704140,18.237307,3.936479,5.278555,10.790945
2015-10-31,14.859745,5.767762,13.797121,17.487862,NaN,NaN,NaN,2.886591,10.822930,7.731894,...,29.789968,2.362335,11.319361,13.762343,NaN,2.883091,19.972151,4.224756,4.919818,11.831775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-31,15.199160,21.959999,15.540000,103.446976,19.782196,14.92,16.129999,14.937753,36.464268,15.902454,...,13.410000,7.230000,66.902298,NaN,17.790615,3.130000,40.199505,NaN,40.221539,16.129999
2022-11-30,15.123164,16.750000,10.560000,88.667427,20.011757,13.83,12.280000,12.643456,34.919239,13.163695,...,14.200000,7.820000,85.419281,NaN,16.113911,2.180000,37.027138,NaN,38.943398,11.500000
2022-12-31,14.520000,15.080000,9.650000,78.250000,19.469999,14.73,11.010000,13.146019,34.730000,12.902847,...,12.610000,7.160000,88.879997,NaN,15.550000,2.400000,37.319073,NaN,38.509998,10.170000
2023-01-31,13.660000,13.610000,1.750000,87.599998,19.650000,15.41,11.850000,12.960000,40.700001,12.602529,...,13.190000,8.530000,94.510002,NaN,16.459999,2.400000,41.820000,NaN,38.240002,10.330000
2023-02-28,13.080000,10.020000,1.220000,78.730003,19.010000,15.18,8.030000,11.370000,42.400002,12.220000,...,12.890000,7.300000,89.190002,NaN,15.580000,2.290000,40.480000,NaN,38.779999,8.380000

In [22]:
#adicionando uma linha
dados_cotacoes_mensais = dados_cotacoes_mensais.append(ultima_linha)

#excluindo uma linha
dados_cotacoes_mensais = dados_cotacoes_mensais.drop("2023-01-31", axis = 0)


dados_cotacoes_mensais

,ABEV3.SA,ALPA4.SA,AMER3.SA,ARZZ3.SA,ASAI3.SA,AURE3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,...,UGPA3.SA,USIM5.SA,VALE3.SA,VALE5.SA,VBBR3.SA,VIIA3.SA,VIVT3.SA,VVAR11.SA,WEGE3.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2015-06-30,14.668835,5.577976,19.304613,19.890100,NaN,NaN,NaN,2.914593,16.064671,9.204789,...,29.088478,3.501015,11.896464,14.912727,NaN,6.839885,21.685192,11.133475,6.445274,13.737409
2015-07-31,15.039612,5.267336,17.118650,17.744524,NaN,NaN,NaN,2.612393,14.589215,9.105167,...,31.078415,3.339560,11.623284,14.022558,NaN,7.655103,22.663952,8.598622,6.371393,10.890436
2015-08-31,14.746079,5.139030,14.762350,18.220686,NaN,NaN,NaN,2.729601,11.887418,8.290726,...,28.220438,2.532288,11.655804,13.543973,NaN,7.655103,20.284359,6.769551,5.703947,9.543482
2015-09-30,15.116618,4.578724,14.062085,16.571829,NaN,NaN,NaN,2.805563,10.301101,7.785673,...,29.701042,2.846699,10.784221,12.749521,NaN,2.704140,18.237307,3.936479,5.278555,10.790945
2015-10-31,14.859745,5.767762,13.797121,17.487862,NaN,NaN,NaN,2.886591,10.822930,7.731894,...,29.789968,2.362335,11.319361,13.762343,NaN,2.883091,19.972151,4.224756,4.919818,11.831775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-31,15.199160,21.959999,15.540000,103.446976,19.782196,14.92,16.129999,14.937753,36.464268,15.902454,...,13.410000,7.230000,66.902298,NaN,17.790615,3.130000,40.199505,NaN,40.221539,16.129999
2022-11-30,15.123164,16.750000,10.560000,88.667427,20.011757,13.83,12.280000,12.643456,34.919239,13.163695,...,14.200000,7.820000,85.419281,NaN,16.113911,2.180000,37.027138,NaN,38.943398,11.500000
2022-12-31,14.520000,15.080000,9.650000,78.250000,19.469999,14.73,11.010000,13.146019,34.730000,12.902847,...,12.610000,7.160000,88.879997,NaN,15.550000,2.400000,37.319073,NaN,38.509998,10.170000
2023-02-28,13.080000,10.020000,1.220000,78.730003,19.010000,15.18,8.030000,11.370000,42.400002,12.220000,...,12.890000,7.300000,89.190002,NaN,15.580000,2.290000,40.480000,NaN,38.779999,8.380000
2023-02-16,13.080000,10.020000,1.220000,78.730003,19.010000,15.18,8.030000,11.370000,42.400002,12.220000,...,12.890000,7.300000,89.190002,NaN,15.580000,2.290000,40.480000,NaN,38.779999,8.380000

In [23]:
#extraindo datas das carteiras

datas_carteiras = list(dados_cotacoes_mensais.index)[6:]
datas_carteiras

[Timestamp('2015-12-31 00:00:00'),
 Timestamp('2016-01-31 00:00:00'),
 Timestamp('2016-02-29 00:00:00'),
 Timestamp('2016-03-31 00:00:00'),
 Timestamp('2016-04-30 00:00:00'),
 Timestamp('2016-05-31 00:00:00'),
 Timestamp('2016-06-30 00:00:00'),
 Timestamp('2016-07-31 00:00:00'),
 Timestamp('2016-08-31 00:00:00'),
 Timestamp('2016-09-30 00:00:00'),
 Timestamp('2016-10-31 00:00:00'),
 Timestamp('2016-11-30 00:00:00'),
 Timestamp('2016-12-31 00:00:00'),
 Timestamp('2017-01-31 00:00:00'),
 Timestamp('2017-02-28 00:00:00'),
 Timestamp('2017-03-31 00:00:00'),
 Timestamp('2017-04-30 00:00:00'),
 Timestamp('2017-05-31 00:00:00'),
 Timestamp('2017-06-30 00:00:00'),
 Timestamp('2017-07-31 00:00:00'),
 Timestamp('2017-08-31 00:00:00'),
 Timestamp('2017-09-30 00:00:00'),
 Timestamp('2017-10-31 00:00:00'),
 Timestamp('2017-11-30 00:00:00'),
 Timestamp('2017-12-31 00:00:00'),
 Timestamp('2018-01-31 00:00:00'),
 Timestamp('2018-02-28 00:00:00'),
 Timestamp('2018-03-31 00:00:00'),
 Timestamp('2018-04-30 00:00:00'),
 Timestamp('2018-05-31 00:00:00'),
 Timestamp('2018-06-30 00:00:00'),
 Timestamp('2018-07-31 00:00:00'),
 Timestamp('2018-08-31 00:00:00'),
 Timestamp('2018-09-30 00:00:00'),
 Timestamp('2018-10-31 00:00:00'),
 Timestamp('2018-11-30 00:00:00'),
 Timestamp('2018-12-31 00:00:00'),
 Timestamp('2019-01-31 00:00:00'),
 Timestamp('2019-02-28 00:00:00'),
 Timestamp('2019-03-31 00:00:00'),
 Timestamp('2019-04-30 00:00:00'),
 Timestamp('2019-05-31 00:00:00'),
 Timestamp('2019-06-30 00:00:00'),
 Timestamp('2019-07-31 00:00:00'),
 Timestamp('2019-08-31 00:00:00'),
 Timestamp('2019-09-30 00:00:00'),
 Timestamp('2019-10-31 00:00:00'),
 Timestamp('2019-11-30 00:00:00'),
 Timestamp('2019-12-31 00:00:00'),
 Timestamp('2020-01-31 00:00:00'),
 Timestamp('2020-02-29 00:00:00'),
 Timestamp('2020-03-31 00:00:00'),
 Timestamp('2020-04-30 00:00:00'),
 Timestamp('2020-05-31 00:00:00'),
 Timestamp('2020-06-30 00:00:00'),
 Timestamp('2020-07-31 00:00:00'),
 Timestamp('2020-08-31 00:00:00'),
 Timestamp('2020-09-30 00:00:00'),
 Timestamp('2020-10-31 00:00:00'),
 Timestamp('2020-11-30 00:00:00'),
 Timestamp('2020-12-31 00:00:00'),
 Timestamp('2021-01-31 00:00:00'),
 Timestamp('2021-02-28 00:00:00'),
 Timestamp('2021-03-31 00:00:00'),
 Timestamp('2021-04-30 00:00:00'),
 Timestamp('2021-05-31 00:00:00'),
 Timestamp('2021-06-30 00:00:00'),
 Timestamp('2021-07-31 00:00:00'),
 Timestamp('2021-08-31 00:00:00'),
 Timestamp('2021-09-30 00:00:00'),
 Timestamp('2021-10-31 00:00:00'),
 Timestamp('2021-11-30 00:00:00'),
 Timestamp('2021-12-31 00:00:00'),
 Timestamp('2022-01-31 00:00:00'),
 Timestamp('2022-02-28 00:00:00'),
 Timestamp('2022-03-31 00:00:00'),
 Timestamp('2022-04-30 00:00:00'),
 Timestamp('2022-05-31 00:00:00'),
 Timestamp('2022-06-30 00:00:00'),
 Timestamp('2022-07-31 00:00:00'),
 Timestamp('2022-08-31 00:00:00'),
 Timestamp('2022-09-30 00:00:00'),
 Timestamp('2022-10-31 00:00:00'),
 Timestamp('2022-11-30 00:00:00'),
 Timestamp('2022-12-31 00:00:00'),
 Timestamp('2023-02-28 00:00:00'),
 Timestamp('2023-02-16 00:00:00')]

In [24]:
#preenchendo NAs com zero para calcular retorno

dados_cotacoes_mensais = dados_cotacoes_mensais.fillna(0)

dados_cotacoes_mensais

,ABEV3.SA,ALPA4.SA,AMER3.SA,ARZZ3.SA,ASAI3.SA,AURE3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,...,UGPA3.SA,USIM5.SA,VALE3.SA,VALE5.SA,VBBR3.SA,VIIA3.SA,VIVT3.SA,VVAR11.SA,WEGE3.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2015-06-30,14.668835,5.577976,19.304613,19.890100,0.000000,0.00,0.000000,2.914593,16.064671,9.204789,...,29.088478,3.501015,11.896464,14.912727,0.000000,6.839885,21.685192,11.133475,6.445274,13.737409
2015-07-31,15.039612,5.267336,17.118650,17.744524,0.000000,0.00,0.000000,2.612393,14.589215,9.105167,...,31.078415,3.339560,11.623284,14.022558,0.000000,7.655103,22.663952,8.598622,6.371393,10.890436
2015-08-31,14.746079,5.139030,14.762350,18.220686,0.000000,0.00,0.000000,2.729601,11.887418,8.290726,...,28.220438,2.532288,11.655804,13.543973,0.000000,7.655103,20.284359,6.769551,5.703947,9.543482
2015-09-30,15.116618,4.578724,14.062085,16.571829,0.000000,0.00,0.000000,2.805563,10.301101,7.785673,...,29.701042,2.846699,10.784221,12.749521,0.000000,2.704140,18.237307,3.936479,5.278555,10.790945
2015-10-31,14.859745,5.767762,13.797121,17.487862,0.000000,0.00,0.000000,2.886591,10.822930,7.731894,...,29.789968,2.362335,11.319361,13.762343,0.000000,2.883091,19.972151,4.224756,4.919818,11.831775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-31,15.199160,21.959999,15.540000,103.446976,19.782196,14.92,16.129999,14.937753,36.464268,15.902454,...,13.410000,7.230000,66.902298,0.000000,17.790615,3.130000,40.199505,0.000000,40.221539,16.129999
2022-11-30,15.123164,16.750000,10.560000,88.667427,20.011757,13.83,12.280000,12.643456,34.919239,13.163695,...,14.200000,7.820000,85.419281,0.000000,16.113911,2.180000,37.027138,0.000000,38.943398,11.500000
2022-12-31,14.520000,15.080000,9.650000,78.250000,19.469999,14.73,11.010000,13.146019,34.730000,12.902847,...,12.610000,7.160000,88.879997,0.000000,15.550000,2.400000,37.319073,0.000000,38.509998,10.170000
2023-02-28,13.080000,10.020000,1.220000,78.730003,19.010000,15.18,8.030000,11.370000,42.400002,12.220000,...,12.890000,7.300000,89.190002,0.000000,15.580000,2.290000,40.480000,0.000000,38.779999,8.380000
2023-02-16,13.080000,10.020000,1.220000,78.730003,19.010000,15.18,8.030000,11.370000,42.400002,12.220000,...,12.890000,7.300000,89.190002,0.000000,15.580000,2.290000,40.480000,0.000000,38.779999,8.380000

In [25]:
#calculando retorno mensal

for i, nome_empresa in enumerate(dados_cotacoes_mensais.columns):

    if i == 0:

      retornos = dados_cotacoes_mensais[nome_empresa].pct_change()

      retornos = retornos.replace([np.inf, -np.inf, -1], 0)

      df_retornos = pd.DataFrame(data = {nome_empresa: retornos}, index = dados_cotacoes_mensais.index)

    else:
    
      df_retornos[nome_empresa] = dados_cotacoes_mensais[nome_empresa].pct_change().replace([np.inf, -np.inf, -1], 0)


df_retornos

,ABEV3.SA,ALPA4.SA,AMER3.SA,ARZZ3.SA,ASAI3.SA,AURE3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,...,UGPA3.SA,USIM5.SA,VALE3.SA,VALE5.SA,VBBR3.SA,VIIA3.SA,VIVT3.SA,VVAR11.SA,WEGE3.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2015-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-07-31,0.025277,-0.055690,-0.113235,-0.107872,NaN,NaN,NaN,-0.103685,-0.091845,-0.010823,...,0.068410,-0.046117,-0.022963,-0.059692,NaN,0.119186,0.045135,-0.227679,-0.011463,-0.207242
2015-08-31,-0.019517,-0.024359,-0.137645,0.026834,NaN,NaN,NaN,0.044866,-0.185191,-0.089448,...,-0.091960,-0.241730,0.002798,-0.034130,NaN,0.000000,-0.104995,-0.212717,-0.104757,-0.123682
2015-09-30,0.025128,-0.109029,-0.047436,-0.090494,NaN,NaN,NaN,0.027829,-0.133445,-0.060918,...,0.052466,0.124161,-0.074777,-0.058657,NaN,-0.646753,-0.100918,-0.418502,-0.074578,0.130714
2015-10-31,-0.016993,0.259688,-0.018842,0.055277,NaN,NaN,NaN,0.028881,0.050658,-0.006907,...,0.002994,-0.170149,0.049623,0.079440,NaN,0.066177,0.095126,0.073232,-0.067961,0.096454
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-31,0.029601,0.032440,-0.084806,0.061884,0.129345,0.101107,0.095788,0.152490,-0.038941,0.021246,...,0.143223,-0.038564,-0.068157,NaN,0.057971,-0.018809,0.020252,NaN,0.253267,0.116263
2022-11-30,-0.005000,-0.237250,-0.320463,-0.142871,0.011604,-0.073056,-0.238686,-0.153590,-0.042371,-0.172222,...,0.058911,0.081604,0.276776,NaN,-0.094247,-0.303514,-0.078916,NaN,-0.031778,-0.287043
2022-12-31,-0.039883,-0.099701,-0.086174,-0.117489,-0.027072,0.065076,-0.103420,0.039749,-0.005419,-0.019816,...,-0.111972,-0.084399,0.040514,NaN,-0.034995,0.100917,0.007884,NaN,-0.011129,-0.115652
2023-02-28,-0.099174,-0.335544,-0.873575,0.006134,-0.023626,0.030550,-0.270663,-0.135099,0.220847,-0.052922,...,0.022205,0.019553,0.003488,NaN,0.001929,-0.045833,0.084700,NaN,0.007011,-0.176008
2023-02-16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,NaN,0.000000,0.000000

In [26]:
#calculando retorno 6 meses

for i, nome_empresa in enumerate(dados_cotacoes_mensais.columns):

    if i == 0:

      retornos = dados_cotacoes_mensais[nome_empresa].pct_change(periods = 6)

      retornos = retornos.replace([np.inf, -np.inf, -1], 0)

      df_retornos_6m = pd.DataFrame(data = {nome_empresa: retornos}, index = dados_cotacoes_mensais.index)

    else:
    
      df_retornos_6m[nome_empresa] = dados_cotacoes_mensais[nome_empresa].pct_change(periods = 6).replace([np.inf, -np.inf, -1], 0)


df_retornos_6m.head(10)

,ABEV3.SA,ALPA4.SA,AMER3.SA,ARZZ3.SA,ASAI3.SA,AURE3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,...,UGPA3.SA,USIM5.SA,VALE3.SA,VALE5.SA,VBBR3.SA,VIIA3.SA,VIVT3.SA,VVAR11.SA,WEGE3.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2015-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-31,-0.044826,-0.076286,-0.253431,-0.113005,NaN,NaN,NaN,-0.019676,-0.362492,-0.235068,...,-0.076003,-0.623786,-0.273276,-0.325780,NaN,-0.781977,-0.067328,-0.708036,-0.204485,-0.222841
2016-01-31,-0.026099,0.001545,-0.266998,-0.100444,NaN,NaN,NaN,0.030454,-0.340404,-0.260394,...,-0.150474,-0.783715,-0.445144,-0.493539,NaN,-0.838961,-0.182059,-0.662428,-0.167808,-0.177091
2016-02-29,-0.054421,0.251857,-0.259615,-0.178820,NaN,NaN,NaN,0.116932,-0.208609,-0.034314,...,-0.003877,-0.697987,-0.327719,-0.380042,NaN,-0.707792,0.000862,-0.364170,-0.202454,0.023256
2016-03-31,-0.016942,0.232223,-0.044415,0.183738,NaN,NaN,NaN,0.435515,0.347493,0.330233,...,0.052332,-0.459701,-0.067891,-0.124446,NaN,-0.110294,0.258974,0.406566,-0.078546,-0.159574

In [27]:
df_retornos = df_retornos.loc["2015-12-31": ]
df_retornos_6m = df_retornos_6m.loc["2015-12-31": ]

df_retornos_6m

,ABEV3.SA,ALPA4.SA,AMER3.SA,ARZZ3.SA,ASAI3.SA,AURE3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,...,UGPA3.SA,USIM5.SA,VALE3.SA,VALE5.SA,VBBR3.SA,VIIA3.SA,VIVT3.SA,VVAR11.SA,WEGE3.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2015-12-31,-0.044826,-0.076286,-0.253431,-0.113005,NaN,NaN,NaN,-0.019676,-0.362492,-0.235068,...,-0.076003,-0.623786,-0.273276,-0.325780,NaN,-0.781977,-0.067328,-0.708036,-0.204485,-0.222841
2016-01-31,-0.026099,0.001545,-0.266998,-0.100444,NaN,NaN,NaN,0.030454,-0.340404,-0.260394,...,-0.150474,-0.783715,-0.445144,-0.493539,NaN,-0.838961,-0.182059,-0.662428,-0.167808,-0.177091
2016-02-29,-0.054421,0.251857,-0.259615,-0.178820,NaN,NaN,NaN,0.116932,-0.208609,-0.034314,...,-0.003877,-0.697987,-0.327719,-0.380042,NaN,-0.707792,0.000862,-0.364170,-0.202454,0.023256
2016-03-31,-0.016942,0.232223,-0.044415,0.183738,NaN,NaN,NaN,0.435515,0.347493,0.330233,...,0.052332,-0.459701,-0.067891,-0.124446,NaN,-0.110294,0.258974,0.406566,-0.078546,-0.159574
2016-04-30,0.031436,0.167527,-0.060357,0.164968,NaN,NaN,NaN,0.561556,0.434325,0.376729,...,0.087326,-0.100719,0.154162,0.121882,NaN,0.024346,0.138833,0.442703,0.068157,-0.207022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-31,0.101928,0.120408,-0.352500,0.184724,0.297120,0.023815,-0.265817,0.151202,0.140424,0.136441,...,0.057887,-0.360743,-0.152247,NaN,-0.119768,0.053872,-0.213826,NaN,0.349226,0.000620
2022-11-30,0.121917,-0.229885,-0.474627,0.127067,0.265783,-0.009312,-0.389359,0.014829,-0.013285,-0.170037,...,-0.011830,-0.286496,0.045730,NaN,-0.133827,-0.305732,-0.246783,NaN,0.549908,-0.289246
2022-12-31,0.140676,-0.212121,-0.281459,0.146957,0.367008,0.081498,-0.110662,0.215158,0.068641,-0.056897,...,0.024370,-0.172254,0.225247,NaN,-0.027580,0.250000,-0.176479,NaN,0.467672,-0.221882
2023-02-28,-0.077751,-0.544338,-0.912857,0.004819,0.201661,0.069767,-0.315431,0.038670,0.210707,-0.113426,...,0.015761,-0.152149,0.349564,NaN,-0.022193,-0.045833,-0.063211,NaN,0.387036,-0.367547
2023-02-16,-0.098285,-0.514535,-0.925337,-0.139270,0.035689,-0.012362,-0.513038,-0.027945,0.039440,-0.191073,...,-0.047302,-0.089776,0.387497,NaN,-0.113263,-0.288820,0.015576,NaN,0.374779,-0.319253

In [28]:
dados_cotacoes_mensais = dados_cotacoes_mensais.reset_index()

df_retornos = df_retornos.reset_index()
df_retornos_6m = df_retornos_6m.reset_index()


dados_cotacoes_mensais = pd.melt(dados_cotacoes_mensais, id_vars= "Date", var_name= "cod", value_name= "cotacao")
df_retornos = pd.melt(df_retornos, id_vars= "Date", var_name= "cod", value_name= "retorno_1m")
df_retornos_6m = pd.melt(df_retornos_6m, id_vars= "Date", var_name= "cod", value_name= "retorno_6m")

In [29]:
dados_cotacoes_mensais = dados_cotacoes_mensais.dropna()
df_retornos = df_retornos.dropna()
df_retornos_6m = df_retornos_6m.dropna()

dados_cotacoes_mensais

           Date       cod    cotacao
0    2015-06-30  ABEV3.SA  14.668835
1    2015-07-31  ABEV3.SA  15.039612
2    2015-08-31  ABEV3.SA  14.746079
3    2015-09-30  ABEV3.SA  15.116618
4    2015-10-31  ABEV3.SA  14.859745
...         ...       ...        ...
9946 2022-10-31  YDUQ3.SA  16.129999
9947 2022-11-30  YDUQ3.SA  11.500000
9948 2022-12-31  YDUQ3.SA  10.170000
9949 2023-02-28  YDUQ3.SA   8.380000
9950 2023-02-16  YDUQ3.SA   8.380000

[9951 rows x 3 columns]

In [14]:
lista_retornos = []

#Logica: Pega os codigos de negociação -> Acha os retornos 6M -> Filtra os 10 maiores -> Calcula o retorno de 1 mês dessa carteira -> Repete

for indice, mes in enumerate(datas_carteiras):

    #pegando empresas do ibov mes a mes

    empresas_ibov = tickers[intervalo_tempo[indice-1]]

    empresas_ibov = list(empresas_ibov.dropna().values) 

    empresas_ibov = [empresa + ".SA" for empresa in empresas_ibov] #quero x a cada y

    #pegando retornos 6 meses pra criar o ranking

    retornos_empresas_ibov_esse_ano = df_retornos_6m[(df_retornos_6m["cod"].isin(empresas_ibov)) & (df_retornos_6m['Date'] == mes)]

    #pegando os 10 maiores retornos

    dez_maiores_retornos = retornos_empresas_ibov_esse_ano.sort_values(by = "retorno_6m", ascending = False).head(10)

    tickers_dez_maiores_retornos = dez_maiores_retornos["cod"].to_list()

    #calculando retorno da carteira 

    if indice != (len(datas_carteiras) - 1): #A carteira de sexta não tem retorno

      retornos_12m_seguintes = df_retornos[(df_retornos["cod"].isin(tickers_dez_maiores_retornos)) & (df_retornos['Date'] == datas_carteiras[indice + 1])]

      retorno_mes = np.mean(retornos_12m_seguintes['retorno_1m'])

      df_retorno_modelo = pd.DataFrame(data = {"retorno": retorno_mes}, index = [(mes + relativedelta(months=1))])

      lista_retornos.append(df_retorno_modelo)

    print(dez_maiores_retornos)
retornos_modelo = pd.concat(lista_retornos)

retornos_modelo.mean()*100

           Date        cod  retorno_6m
1653 2015-12-31   BRKM5.SA    1.027900
3480 2015-12-31   EMBR3.SA    0.279962
5394 2015-12-31  KLBN11.SA    0.249771
7830 2015-12-31   SMTO3.SA    0.243193
3393 2015-12-31   ELET6.SA    0.225352
1044 2015-12-31   BEEF3.SA    0.167691
7656 2015-12-31   SBSP3.SA    0.147273
5916 2015-12-31   MRFG3.SA    0.114035
6003 2015-12-31   MRVE3.SA    0.112821
3567 2015-12-31   ENBR3.SA    0.048720
           Date       cod  retorno_6m
1654 2016-01-31  BRKM5.SA    0.913875
2698 2016-01-31  CSAN3.SA    0.232301
7657 2016-01-31  SBSP3.SA    0.220378
3481 2016-01-31  EMBR3.SA    0.207090
6004 2016-01-31  MRVE3.SA    0.185233
5917 2016-01-31  MRFG3.SA    0.150943
4699 2016-01-31  HYPE3.SA    0.103159
3829 2016-01-31  EQTL3.SA    0.043769
4003 2016-01-31  FIBR3.SA    0.036790
610  2016-01-31  B3SA3.SA    0.030453
           Date        cod  retorno_6m
1655 2016-02-29   BRKM5.SA    0.812366
6005 2016-02-29   MRVE3.SA    0.664050
2699 2016-02-29   CSAN3.SA    0.547191
4700 2016-02-29   HYPE3.SA    0.530055
2786 2016-02-29   CSNA3.SA    0.485714
7658 2016-02-29   SBSP3.SA    0.437381
3482 2016-02-29   EMBR3.SA    0.316026
1742 2016-02-29   BRML3.SA    0.201786
6962 2016-02-29   RADL3.SA    0.166301
7484 2016-02-29  SANB11.SA    0.155541
           Date        cod  retorno_6m
6006 2016-03-31   MRVE3.SA    0.932677
4701 2016-03-31   HYPE3.SA    0.847513
2787 2016-03-31   CSNA3.SA    0.818878
2700 2016-03-31   CSAN3.SA    0.605572
7659 2016-03-31   SBSP3.SA    0.513889
2352 2016-03-31   COGN3.SA    0.501530
612  2016-03-31   B3SA3.SA    0.435515
7485 2016-03-31  SANB11.SA    0.416242
1743 2016-03-31   BRML3.SA    0.410134
1656 2016-03-31   BRKM5.SA    0.404319
           Date       cod  retorno_6m
2788 2016-04-30  CSNA3.SA    2.027649
4702 2016-04-30  HYPE3.SA    0.736056
6007 2016-04-30  MRVE3.SA    0.619946
7660 2016-04-30  SBSP3.SA    0.591904
613  2016-04-30  B3SA3.SA    0.561556
1744 2016-04-30  BRML3.SA    0.511607
4267 2016-04-30  GGBR4.SA    0.448729
700  2016-04-30  BBAS3.SA    0.434325
6094 2016-04-30  MULT3.SA    0.426824
874  2016-04-30  BBDC4.SA    0.421211
           Date       cod  retorno_6m
3137 2016-05-31  ECOR3.SA    0.500956
6965 2016-05-31  RADL3.SA    0.465169
614  2016-05-31  B3SA3.SA    0.438681
2702 2016-05-31  CSAN3.SA    0.432475
7661 2016-05-31  SBSP3.SA    0.365267
3833 2016-05-31  EQTL3.SA    0.333666
2963 2016-05-31  CYRE3.SA    0.333556
1484 2016-05-31  BRAP4.SA    0.310151
6095 2016-05-31  MULT3.SA    0.306290
4703 2016-05-31  HYPE3.SA    0.282781
           Date       cod  retorno_6m
2790 2016-06-30  CSNA3.SA    0.955000
6966 2016-06-30  RADL3.SA    0.788933
1485 2016-06-30  BRAP4.SA    0.773547
615  2016-06-30  B3SA3.SA    0.662610
3138 2016-06-30  ECOR3.SA    0.646365
6096 2016-06-30  MULT3.SA    0.585789
7662 2016-06-30  SBSP3.SA    0.550644
1746 2016-06-30  BRML3.SA    0.504955
789  2016-06-30  BBDC3.SA    0.465239
876  2016-06-30  BBDC4.SA    0.455130
           Date       cod  retorno_6m
8533 2016-07-31  USIM5.SA    3.411764
4444 2016-07-31  GOLL4.SA    2.352941
1486 2016-07-31  BRAP4.SA    2.253013
7054 2016-07-31  RAIL3.SA    2.238095
2791 2016-07-31  CSNA3.SA    2.118310
4357 2016-07-31  GOAU4.SA    1.640777
6532 2016-07-31  PETR4.SA    1.452479
4270 2016-07-31  GGBR4.SA    1.152777
8707 2016-07-31  VALE5.SA    1.073205
3139 2016-07-31  ECOR3.SA    1.057644
           Date       cod  retorno_6m
8534 2016-08-31  USIM5.SA    2.855555
4358 2016-08-31  GOAU4.SA    2.066116
4445 2016-08-31  GOLL4.SA    1.740260
7055 2016-08-31  RAIL3.SA    1.737642
4271 2016-08-31  GGBR4.SA    1.580243
1487 2016-08-31  BRAP4.SA    1.550868
6533 2016-08-31  PETR4.SA    1.500000
6446 2016-08-31  PETR3.SA    1.005442
6881 2016-08-31  QUAL3.SA    0.860250
3140 2016-08-31  ECOR3.SA    0.840708
           Date       cod  retorno_6m
4446 2016-09-30  GOLL4.SA    1.252708
8535 2016-09-30  USIM5.SA    0.950276
7056 2016-09-30  RAIL3.SA    0.897898
6534 2016-09-30  PETR4.SA    0.632972
1488 2016-09-30  BRAP4.SA    0.586992
9231 2016-09-30  YDUQ3.SA    0.552264
3141 2016-09-30  ECOR3.SA    0.491611
6447 2016-09-30  PETR3.SA    0.424271
4359 2016-09-30  GOAU4.SA    0.405738
6882 2016-09-30  QUAL3.SA    0.389746
           Date        cod  retorno_6m
4447 2016-10-31   GOLL4.SA    2.221311
8536 2016-10-31   USIM5.SA    0.804000
6535 2016-10-31   PETR4.SA    0.729228
7057 2016-10-31   RAIL3.SA    0.668224
4360 2016-10-31   GOAU4.SA    0.632303
9232 2016-10-31   YDUQ3.SA    0.559394
1489 2016-10-31   BRAP4.SA    0.532467
2185 2016-10-31   CMIG4.SA    0.498822
6883 2016-10-31   QUAL3.SA    0.456326
7492 2016-10-31  SANB11.SA    0.427548
           Date       cod  retorno_6m
4361 2016-11-30  GOAU4.SA    2.025906
8537 2016-11-30  USIM5.SA    1.485030
4274 2016-11-30  GGBR4.SA    1.443856
4448 2016-11-30  GOLL4.SA    1.387665
8711 2016-11-30  VALE5.SA    1.273132
1490 2016-11-30  BRAP4.SA    1.144907
6536 2016-11-30  PETR4.SA    0.990050
8624 2016-11-30  VALE3.SA    0.973277
2795 2016-11-30  CSNA3.SA    0.900612
6449 2016-11-30  PETR3.SA    0.814342
           Date        cod  retorno_6m
4362 2016-12-31   GOAU4.SA    1.400000
8538 2016-12-31   USIM5.SA    1.081218
1665 2016-12-31   BRKM5.SA    0.890724
4275 2016-12-31   GGBR4.SA    0.842044
8712 2016-12-31   VALE5.SA    0.803103
1491 2016-12-31   BRAP4.SA    0.691075
708  2016-12-31   BBAS3.SA    0.665912
7494 2016-12-31  SANB11.SA    0.636375
8625 2016-12-31   VALE3.SA    0.587639
6537 2016-12-31   PETR4.SA    0.578556
           Date        cod  retorno_6m
4363 2017-01-31   GOAU4.SA    1.066177
8713 2017-01-31   VALE5.SA    1.048776
1492 2017-01-31   BRAP4.SA    0.940971
1666 2017-01-31   BRKM5.SA    0.844771
8626 2017-01-31   VALE3.SA    0.749680
7495 2017-01-31  SANB11.SA    0.602314
4276 2017-01-31   GGBR4.SA    0.581428
709  2017-01-31   BBAS3.SA    0.505815
4015 2017-01-31   FIBR3.SA    0.484083
8539 2017-01-31   USIM5.SA    0.400000
           Date        cod  retorno_6m
6365 2017-02-28   PCAR3.SA    1.339928
1493 2017-02-28   BRAP4.SA    1.298949
8714 2017-02-28   VALE5.SA    1.192017
8627 2017-02-28   VALE3.SA    0.942871
7496 2017-02-28  SANB11.SA    0.580078
4364 2017-02-28   GOAU4.SA    0.579514
710  2017-02-28   BBAS3.SA    0.443920
4277 2017-02-28   GGBR4.SA    0.428321
8540 2017-02-28   USIM5.SA    0.420749
1667 2017-02-28   BRKM5.SA    0.409429
           Date        cod  retorno_6m
1494 2017-03-31   BRAP4.SA    1.260349
8715 2017-03-31   VALE5.SA    0.843938
6366 2017-03-31   PCAR3.SA    0.808126
8628 2017-03-31   VALE3.SA    0.682483
711  2017-03-31   BBAS3.SA    0.495681
4365 2017-03-31   GOAU4.SA    0.443149
7062 2017-03-31   RAIL3.SA    0.352848
4452 2017-03-31   GOLL4.SA    0.336539
1668 2017-03-31   BRKM5.SA    0.329021
7497 2017-03-31  SANB11.SA    0.310814
           Date       cod  retorno_6m
1495 2017-04-30  BRAP4.SA    0.579297
6367 2017-04-30  PCAR3.SA    0.542225
6019 2017-04-30  MRVE3.SA    0.324454
8629 2017-04-30  VALE3.SA    0.293171
8716 2017-04-30  VALE5.SA    0.281326
4453 2017-04-30  GOLL4.SA    0.277354
5932 2017-04-30  MRFG3.SA    0.268893
2974 2017-04-30  CYRE3.SA    0.227907
7063 2017-04-30  RAIL3.SA    0.222689
1669 2017-04-30  BRKM5.SA    0.207641
           Date       cod  retorno_6m
6368 2017-05-31  PCAR3.SA    0.808339
6890 2017-05-31  QUAL3.SA    0.560987
4454 2017-05-31  GOLL4.SA    0.439114
7064 2017-05-31  RAIL3.SA    0.333333
7325 2017-05-31  RENT3.SA    0.332061
1496 2017-05-31  BRAP4.SA    0.320762
5672 2017-05-31  LREN3.SA    0.302394
1757 2017-05-31  BRML3.SA    0.282601
9152 2017-05-31  WEGE3.SA    0.236287
4019 2017-05-31  FIBR3.SA    0.225754
           Date       cod  retorno_6m
6369 2017-06-30  PCAR3.SA    0.808339
4455 2017-06-30  GOLL4.SA    0.634199
6891 2017-06-30  QUAL3.SA    0.524118
1497 2017-06-30  BRAP4.SA    0.421475
7065 2017-06-30  RAIL3.SA    0.408795
7326 2017-06-30  RENT3.SA    0.391728
5673 2017-06-30  LREN3.SA    0.311065
6021 2017-06-30  MRVE3.SA    0.297327
3150 2017-06-30  ECOR3.SA    0.283248
8283 2017-06-30  TIMS3.SA    0.257777
           Date       cod  retorno_6m
6370 2017-07-31  PCAR3.SA    0.847609
6892 2017-07-31  QUAL3.SA    0.626909
7327 2017-07-31  RENT3.SA    0.491474
4456 2017-07-31  GOLL4.SA    0.429712
7066 2017-07-31  RAIL3.SA    0.378667
5674 2017-07-31  LREN3.SA    0.361289
9241 2017-07-31  YDUQ3.SA    0.305310
3151 2017-07-31  ECOR3.SA    0.280343
9154 2017-07-31  WEGE3.SA    0.207017
8284 2017-07-31  TIMS3.SA    0.195917
           Date       cod  retorno_6m
6893 2017-08-31  QUAL3.SA    0.807521
9242 2017-08-31  YDUQ3.SA    0.751729
7328 2017-08-31  RENT3.SA    0.636699
4022 2017-08-31  FIBR3.SA    0.610826
194  2017-08-31  AMER3.SA    0.539228
8546 2017-08-31  USIM5.SA    0.397566
2369 2017-08-31  COGN3.SA    0.342415
4457 2017-08-31  GOLL4.SA    0.336085
5675 2017-08-31  LREN3.SA    0.328763
9155 2017-08-31  WEGE3.SA    0.221719
           Date       cod  retorno_6m
9243 2017-09-30  YDUQ3.SA    0.986667
6894 2017-09-30  QUAL3.SA    0.894510
8547 2017-09-30  USIM5.SA    0.752252
195  2017-09-30  AMER3.SA    0.711741
4458 2017-09-30  GOLL4.SA    0.600719
2370 2017-09-30  COGN3.SA    0.532753
4023 2017-09-30  FIBR3.SA    0.520671
7329 2017-09-30  RENT3.SA    0.464382
5676 2017-09-30  LREN3.SA    0.438090
7068 2017-09-30  RAIL3.SA    0.414035
           Date       cod  retorno_6m
8548 2017-10-31  USIM5.SA    1.068075
4024 2017-10-31  FIBR3.SA    0.823969
9244 2017-10-31  YDUQ3.SA    0.644980
6895 2017-10-31  QUAL3.SA    0.598590
196  2017-10-31  AMER3.SA    0.586697
1675 2017-10-31  BRKM5.SA    0.533685
7069 2017-10-31  RAIL3.SA    0.454754
4459 2017-10-31  GOLL4.SA    0.379482
7330 2017-10-31  RENT3.SA    0.293656
3154 2017-10-31  ECOR3.SA    0.292373
           Date       cod  retorno_6m
8549 2017-11-30  USIM5.SA    1.156171
4460 2017-11-30  GOLL4.SA    0.800000
9245 2017-11-30  YDUQ3.SA    0.762507
7070 2017-11-30  RAIL3.SA    0.535377
7331 2017-11-30  RENT3.SA    0.391714
1676 2017-11-30  BRKM5.SA    0.370359
3329 2017-11-30  ELET3.SA    0.362182
197  2017-11-30  AMER3.SA    0.361045
3155 2017-11-30  ECOR3.SA    0.332880
1502 2017-11-30  BRAP4.SA    0.323745
           Date       cod  retorno_6m
9246 2017-12-31  YDUQ3.SA    1.244870
8550 2017-12-31  USIM5.SA    0.978261
4461 2017-12-31  GOLL4.SA    0.933775
198  2017-12-31  AMER3.SA    0.752137
3330 2017-12-31  ELET3.SA    0.553414
5157 2017-12-31  JBSS3.SA    0.502297
7071 2017-12-31  RAIL3.SA    0.499422
7332 2017-12-31  RENT3.SA    0.480641
1503 2017-12-31  BRAP4.SA    0.441349
4026 2017-12-31  FIBR3.SA    0.415262
           Date        cod  retorno_6m
8551 2018-01-31   USIM5.SA    1.294004
4462 2018-01-31   GOLL4.SA    1.023464
9247 2018-01-31   YDUQ3.SA    0.718137
4027 2018-01-31   FIBR3.SA    0.659008
199  2018-01-31   AMER3.SA    0.597745
6463 2018-01-31   PETR3.SA    0.543478
3331 2018-01-31   ELET3.SA    0.505926
7333 2018-01-31   RENT3.SA    0.499369
6550 2018-01-31   PETR4.SA    0.482317
7507 2018-01-31  SANB11.SA    0.475688
           Date        cod  retorno_6m
8552 2018-02-28   USIM5.SA    0.788099
4463 2018-02-28   GOLL4.SA    0.694616
9074 2018-02-28  VVAR11.SA    0.665880
6464 2018-02-28   PETR3.SA    0.657122
6551 2018-02-28   PETR4.SA    0.572161
4028 2018-02-28   FIBR3.SA    0.475712
4289 2018-02-28   GGBR4.SA    0.406539
3332 2018-02-28   ELET3.SA    0.405789
4376 2018-02-28   GOAU4.SA    0.398003
7073 2018-02-28   RAIL3.SA    0.378509
           Date        cod  retorno_6m
8118 2018-03-31   SUZB3.SA    0.684147
4464 2018-03-31   GOLL4.SA    0.621723
4029 2018-03-31   FIBR3.SA    0.517620
7509 2018-03-31  SANB11.SA    0.508985
7335 2018-03-31   RENT3.SA    0.500997
6465 2018-03-31   PETR3.SA    0.477546
4290 2018-03-31   GGBR4.SA    0.410620
8553 2018-03-31   USIM5.SA    0.403599
6552 2018-03-31   PETR4.SA    0.399347
4377 2018-03-31   GOAU4.SA    0.355317
           Date       cod  retorno_6m
8119 2018-04-30  SUZB3.SA    1.082884
5857 2018-04-30  MGLU3.SA    0.688493
1507 2018-04-30  BRAP4.SA    0.587761
8641 2018-04-30  VALE3.SA    0.549804
4378 2018-04-30  GOAU4.SA    0.536682
4291 2018-04-30  GGBR4.SA    0.527733
7336 2018-04-30  RENT3.SA    0.453589
3508 2018-04-30  EMBR3.SA    0.425001
6466 2018-04-30  PETR3.SA    0.413892
4465 2018-04-30  GOLL4.SA    0.402166
           Date       cod  retorno_6m
8120 2018-05-31  SUZB3.SA    1.473336
5858 2018-05-31  MGLU3.SA    0.924786
4031 2018-05-31  FIBR3.SA    0.577548
203  2018-05-31  AMER3.SA    0.474695
8642 2018-05-31  VALE3.SA    0.472742
3509 2018-05-31  EMBR3.SA    0.449378
6467 2018-05-31  PETR3.SA    0.393614
4379 2018-05-31  GOAU4.SA    0.350074
4292 2018-05-31  GGBR4.SA    0.344493
1508 2018-05-31  BRAP4.SA    0.318865
           Date        cod  retorno_6m
8121 2018-06-30   SUZB3.SA    1.417718
5859 2018-06-30   MGLU3.SA    0.599887
4032 2018-06-30   FIBR3.SA    0.526853
204  2018-06-30   AMER3.SA    0.312195
8643 2018-06-30   VALE3.SA    0.245737
1683 2018-06-30   BRKM5.SA    0.235063
3510 2018-06-30   EMBR3.SA    0.218883
6468 2018-06-30   PETR3.SA    0.150407
2466 2018-06-30   CPFE3.SA    0.132606
5424 2018-06-30  KLBN11.SA    0.131681
           Date        cod  retorno_6m
8122 2018-07-31   SUZB3.SA    1.166753
5860 2018-07-31   MGLU3.SA    0.568410
4033 2018-07-31   FIBR3.SA    0.357500
8644 2018-07-31   VALE3.SA    0.338070
205  2018-07-31   AMER3.SA    0.324706
5947 2018-07-31   MRFG3.SA    0.204112
2206 2018-07-31   CMIG4.SA    0.166303
4294 2018-07-31   GGBR4.SA    0.165924
1684 2018-07-31   BRKM5.SA    0.154976
5425 2018-07-31  KLBN11.SA    0.152572
           Date        cod  retorno_6m
8123 2018-08-31   SUZB3.SA    1.185676
5861 2018-08-31   MGLU3.SA    0.434478
1685 2018-08-31   BRKM5.SA    0.329916
4034 2018-08-31   FIBR3.SA    0.292599
8645 2018-08-31   VALE3.SA    0.238451
5426 2018-08-31  KLBN11.SA    0.211196
206  2018-08-31   AMER3.SA    0.110551
3599 2018-08-31   ENBR3.SA    0.085849
9167 2018-08-31   WEGE3.SA    0.076440
8210 2018-08-31  TAEE11.SA    0.065069
           Date       cod  retorno_6m
8646 2018-09-30  VALE3.SA    0.458048
8124 2018-09-30  SUZB3.SA    0.448207
1686 2018-09-30  BRKM5.SA    0.269960
5862 2018-09-30  MGLU3.SA    0.254497
1512 2018-09-30  BRAP4.SA    0.220204
4035 2018-09-30  FIBR3.SA    0.169150
9168 2018-09-30  WEGE3.SA    0.145669
7080 2018-09-30  RAIL3.SA    0.139164
2817 2018-09-30  CSNA3.SA    0.139096
4383 2018-09-30  GOAU4.SA    0.133624
           Date       cod  retorno_6m
5863 2018-10-31  MGLU3.SA    0.581858
2209 2018-10-31  CMIG4.SA    0.385729
6472 2018-10-31  PETR3.SA    0.235894
3340 2018-10-31  ELET3.SA    0.232302
6559 2018-10-31  PETR4.SA    0.207856
8647 2018-10-31  VALE3.SA    0.198779
208  2018-10-31  AMER3.SA    0.193772
1687 2018-10-31  BRKM5.SA    0.191612
730  2018-10-31  BBAS3.SA    0.190840
5167 2018-10-31  JBSS3.SA    0.177725
           Date       cod  retorno_6m
3428 2018-11-30  ELET6.SA    0.690746
3341 2018-11-30  ELET3.SA    0.669856
2210 2018-11-30  CMIG4.SA    0.657106
4472 2018-11-30  GOLL4.SA    0.601186
5864 2018-11-30  MGLU3.SA    0.518447
209  2018-11-30  AMER3.SA    0.509665
731  2018-11-30  BBAS3.SA    0.506531
2558 2018-11-30  CPLE6.SA    0.388616
6560 2018-11-30  PETR4.SA    0.350131
905  2018-11-30  BBDC4.SA    0.332941
           Date        cod  retorno_6m
4473 2018-12-31   GOLL4.SA    1.408829
3429 2018-12-31   ELET6.SA    1.078967
3342 2018-12-31   ELET3.SA    0.987695
2211 2018-12-31   CMIG4.SA    0.919288
732  2018-12-31   BBAS3.SA    0.663466
210  2018-12-31   AMER3.SA    0.562082
906  2018-12-31   BBDC4.SA    0.481048
7518 2018-12-31  SANB11.SA    0.478732
2994 2018-12-31   CYRE3.SA    0.462869
5691 2018-12-31   LREN3.SA    0.449967
           Date       cod  retorno_6m
3343 2019-01-31  ELET3.SA    1.165605
3430 2019-01-31  ELET6.SA    1.110996
4474 2019-01-31  GOLL4.SA    0.790007
2560 2019-01-31  CPLE6.SA    0.785982
211  2019-01-31  AMER3.SA    0.776199
7693 2019-01-31  SBSP3.SA    0.734800
2212 2019-01-31  CMIG4.SA    0.701178
5170 2019-01-31  JBSS3.SA    0.672949
733  2019-01-31  BBAS3.SA    0.635791
3256 2019-01-31  EGIE3.SA    0.548322
           Date       cod  retorno_6m
4475 2019-02-28  GOLL4.SA    1.378234
3344 2019-02-28  ELET3.SA    1.337548
3431 2019-02-28  ELET6.SA    1.153039
2213 2019-02-28  CMIG4.SA    0.951297
212  2019-02-28  AMER3.SA    0.830053
734  2019-02-28  BBAS3.SA    0.726614
3170 2019-02-28  ECOR3.SA    0.653865
2996 2019-02-28  CYRE3.SA    0.627361
7346 2019-02-28  RENT3.SA    0.613750
7694 2019-02-28  SBSP3.SA    0.612705
           Date       cod  retorno_6m
3345 2019-03-31  ELET3.SA    1.365571
4476 2019-03-31  GOLL4.SA    1.343891
3432 2019-03-31  ELET6.SA    1.033297
2214 2019-03-31  CMIG4.SA    0.962464
7695 2019-03-31  SBSP3.SA    0.780416
2823 2019-03-31  CSNA3.SA    0.739828
735  2019-03-31  BBAS3.SA    0.718592
5172 2019-03-31  JBSS3.SA    0.697228
3258 2019-03-31  EGIE3.SA    0.586926
2997 2019-03-31  CYRE3.SA    0.575764
           Date       cod  retorno_6m
5173 2019-04-30  JBSS3.SA    0.928780
7696 2019-04-30  SBSP3.SA    0.723568
2824 2019-04-30  CSNA3.SA    0.589078
3259 2019-04-30  EGIE3.SA    0.473636
2737 2019-04-30  CSAN3.SA    0.453333
3346 2019-04-30  ELET3.SA    0.428613
1606 2019-04-30  BRFS3.SA    0.417808
3433 2019-04-30  ELET6.SA    0.358478
2215 2019-04-30  CMIG4.SA    0.350896
3607 2019-04-30  ENBR3.SA    0.320043
           Date       cod  retorno_6m
2825 2019-05-31  CSNA3.SA    1.046204
5174 2019-05-31  JBSS3.SA    0.857475
6044 2019-05-31  MRVE3.SA    0.608573
7697 2019-05-31  SBSP3.SA    0.605173
3608 2019-05-31  ENBR3.SA    0.529566
6914 2019-05-31  QUAL3.SA    0.509942
3347 2019-05-31  ELET3.SA    0.446092
7349 2019-05-31  RENT3.SA    0.421986
2738 2019-05-31  CSAN3.SA    0.397863
3260 2019-05-31  EGIE3.SA    0.388510
           Date       cod  retorno_6m
2826 2019-06-30  CSNA3.SA    1.074250
6915 2019-06-30  QUAL3.SA    0.850787
5175 2019-06-30  JBSS3.SA    0.831096
6045 2019-06-30  MRVE3.SA    0.654732
7698 2019-06-30  SBSP3.SA    0.538110
3348 2019-06-30  ELET3.SA    0.493621
651  2019-06-30  B3SA3.SA    0.412527
2739 2019-06-30  CSAN3.SA    0.409406
7350 2019-06-30  RENT3.SA    0.385438
3609 2019-06-30  ENBR3.SA    0.352383
           Date       cod  retorno_6m
2827 2019-07-31  CSNA3.SA    0.778319
4480 2019-07-31  GOLL4.SA    0.657363
5176 2019-07-31  JBSS3.SA    0.650287
6916 2019-07-31  QUAL3.SA    0.498838
3001 2019-07-31  CYRE3.SA    0.482953
5872 2019-07-31  MGLU3.SA    0.476063
1609 2019-07-31  BRFS3.SA    0.419286
6046 2019-07-31  MRVE3.SA    0.412967
565  2019-07-31  AZUL4.SA    0.395311
652  2019-07-31  B3SA3.SA    0.358839
           Date       cod  retorno_6m
5177 2019-08-31  JBSS3.SA    1.207250
6917 2019-08-31  QUAL3.SA    0.973343
1610 2019-08-31  BRFS3.SA    0.854157
8918 2019-08-31  VIIA3.SA    0.687773
5873 2019-08-31  MGLU3.SA    0.677499
3002 2019-08-31  CYRE3.SA    0.522909
5960 2019-08-31  MRFG3.SA    0.518182
6047 2019-08-31  MRVE3.SA    0.514963
7004 2019-08-31  RADL3.SA    0.413939
653  2019-08-31  B3SA3.SA    0.384815
           Date       cod  retorno_6m
6918 2019-09-30  QUAL3.SA    1.120578
5178 2019-09-30  JBSS3.SA    1.059908
8919 2019-09-30  VIIA3.SA    0.876777
5961 2019-09-30  MRFG3.SA    0.842809
5874 2019-09-30  MGLU3.SA    0.718210
1611 2019-09-30  BRFS3.SA    0.686534
3003 2019-09-30  CYRE3.SA    0.528162
2046 2019-09-30  CCRO3.SA    0.506002
7005 2019-09-30  RADL3.SA    0.472898
3177 2019-09-30  ECOR3.SA    0.470282
           Date        cod  retorno_6m
6919 2019-10-31   QUAL3.SA    0.909210
5875 2019-10-31   MGLU3.SA    0.870782
4570 2019-10-31   HAPV3.SA    0.868343
8920 2019-10-31   VIIA3.SA    0.809756
3178 2019-10-31   ECOR3.SA    0.695438
4483 2019-10-31   GOLL4.SA    0.606672
7006 2019-10-31   RADL3.SA    0.597123
1351 2019-10-31  BPAC11.SA    0.596902
3004 2019-10-31   CYRE3.SA    0.565836
568  2019-10-31   AZUL4.SA    0.544706
           Date       cod  retorno_6m
6920 2019-11-30  QUAL3.SA    0.880027
8921 2019-11-30  VIIA3.SA    0.874468
5876 2019-11-30  MGLU3.SA    0.841489

           Date        cod  retorno_6m
2845 2021-01-31   CSNA3.SA    1.481633
583  2021-01-31   AZUL4.SA    0.986214
6847 2021-01-31   PRIO3.SA    0.780500
8587 2021-01-31   USIM5.SA    0.623616
1540 2021-01-31   BRAP4.SA    0.514010
8674 2021-01-31   VALE3.SA    0.509250
8152 2021-01-31   SUZB3.SA    0.477381
4324 2021-01-31   GGBR4.SA    0.348921
5455 2021-01-31  KLBN11.SA    0.343284
7543 2021-01-31  SANB11.SA    0.340850
           Date       cod  retorno_6m
2846 2021-02-28  CSNA3.SA    1.161078
6848 2021-02-28  PRIO3.SA    0.995942
584  2021-02-28  AZUL4.SA    0.828005
3542 2021-02-28  EMBR3.SA    0.666212
8675 2021-02-28  VALE3.SA    0.649986
8588 2021-02-28  USIM5.SA    0.600000
1541 2021-02-28  BRAP4.SA    0.489954
1715 2021-02-28  BRKM5.SA    0.468295
8153 2021-02-28  SUZB3.SA    0.457570
3716 2021-02-28  ENEV3.SA    0.373737
           Date       cod  retorno_6m
6414 2021-03-31  PCAR3.SA    2.593146
6849 2021-03-31  PRIO3.SA    1.644884
2847 2021-03-31  CSNA3.SA    1.296970
3543 2021-03-31  EMBR3.SA    1.245192
1716 2021-03-31  BRKM5.SA    0.909091
8676 2021-03-31  VALE3.SA    0.732085
8589 2021-03-31  USIM5.SA    0.704885
1542 2021-03-31  BRAP4.SA    0.586671
585  2021-03-31  AZUL4.SA    0.552502
8154 2021-03-31  SUZB3.SA    0.504940
           Date       cod  retorno_6m
6415 2021-04-30  PCAR3.SA    3.965392
6850 2021-04-30  PRIO3.SA    1.924010
3544 2021-04-30  EMBR3.SA    1.553897
2848 2021-04-30  CSNA3.SA    1.394839
1717 2021-04-30  BRKM5.SA    1.298599
8590 2021-04-30  USIM5.SA    1.071556
2935 2021-04-30  CVCB3.SA    0.951954
8677 2021-04-30  VALE3.SA    0.881607
586  2021-04-30  AZUL4.SA    0.707317
1543 2021-04-30  BRAP4.SA    0.649687
           Date        cod  retorno_6m
6416 2021-05-31   PCAR3.SA    3.549661
1718 2021-05-31   BRKM5.SA    1.215487
3545 2021-05-31   EMBR3.SA    1.133333
6851 2021-05-31   PRIO3.SA    0.966314
2849 2021-05-31   CSNA3.SA    0.936380
1370 2021-05-31  BPAC11.SA    0.584676
8678 2021-05-31   VALE3.SA    0.537831
3371 2021-05-31   ELET3.SA    0.518790
4328 2021-05-31   GGBR4.SA    0.490937
4415 2021-05-31   GOAU4.SA    0.485928
           Date       cod  retorno_6m
6417 2021-06-30  PCAR3.SA    3.116074
1719 2021-06-30  BRKM5.SA    1.526517
3546 2021-06-30  EMBR3.SA    1.132203
2850 2021-06-30  CSNA3.SA    0.399742
6852 2021-06-30  PRIO3.SA    0.388374
8679 2021-06-30  VALE3.SA    0.380093
2937 2021-06-30  CVCB3.SA    0.346939
5808 2021-06-30  LWSA3.SA    0.345098
5982 2021-06-30  MRFG3.SA    0.333920
8592 2021-06-30  USIM5.SA    0.315233
           Date       cod  retorno_6m
6418 2021-07-31  PCAR3.SA    2.284898
1720 2021-07-31  BRKM5.SA    1.384393
3547 2021-07-31  EMBR3.SA    1.114903
8593 2021-07-31  USIM5.SA    0.567761
2851 2021-07-31  CSNA3.SA    0.558517
3460 2021-07-31  ELET6.SA    0.526152
3373 2021-07-31  ELET3.SA    0.509607
5983 2021-07-31  MRFG3.SA    0.492134
2764 2021-07-31  CSAN3.SA    0.377498
4417 2021-07-31  GOAU4.SA    0.374379
           Date        cod  retorno_6m
6419 2021-08-31   PCAR3.SA    1.727347
1721 2021-08-31   BRKM5.SA    1.111004
3548 2021-08-31   EMBR3.SA    0.914963
5984 2021-08-31   MRFG3.SA    0.490673
8855 2021-08-31   VBBR3.SA    0.463345
6506 2021-08-31   PETR3.SA    0.378978
6593 2021-08-31   PETR4.SA    0.338986
8246 2021-08-31  TAEE11.SA    0.326128
2243 2021-08-31   CMIG4.SA    0.317707
3896 2021-08-31   EQTL3.SA    0.298020
           Date       cod  retorno_6m
3549 2021-09-30  EMBR3.SA    0.650964
5985 2021-09-30  MRFG3.SA    0.569124
1722 2021-09-30  BRKM5.SA    0.495087
6855 2021-09-30  PRIO3.SA    0.355657
5202 2021-09-30  JBSS3.SA    0.306184
417  2021-09-30  ASAI3.SA    0.294397
6507 2021-09-30  PETR3.SA    0.286382
2244 2021-09-30  CMIG4.SA    0.256053
8421 2021-09-30  TOTS3.SA    0.254502
6594 2021-09-30  PETR4.SA    0.237463
           Date       cod  retorno_6m
5986 2021-10-31  MRFG3.SA    0.455368
3550 2021-10-31  EMBR3.SA    0.424026
5203 2021-10-31  JBSS3.SA    0.338784
6856 2021-10-31  PRIO3.SA    0.281393
6508 2021-10-31  PETR3.SA    0.267353
6595 2021-10-31  PETR4.SA    0.217911
70   2021-10-31  ABEV3.SA    0.137216
1636 2021-10-31  BRFS3.SA    0.117364
2245 2021-10-31  CMIG4.SA    0.085612
7987 2021-10-31  SOMA3.SA    0.082508
           Date       cod  retorno_6m
5987 2021-11-30  MRFG3.SA    0.366329
5204 2021-11-30  JBSS3.SA    0.249866
6509 2021-11-30  PETR3.SA    0.196593
6596 2021-11-30  PETR4.SA    0.160508
9032 2021-11-30  VIVT3.SA    0.157651
8336 2021-11-30  TIMS3.SA    0.152576
3638 2021-11-30  ENBR3.SA    0.147453
3551 2021-11-30  EMBR3.SA    0.107639
2594 2021-11-30  CPLE6.SA    0.040109
6857 2021-11-30  PRIO3.SA    0.028383
           Date       cod  retorno_6m
5205 2021-12-31  JBSS3.SA    0.420810
5988 2021-12-31  MRFG3.SA    0.369232
3552 2021-12-31  EMBR3.SA    0.315315
6510 2021-12-31  PETR3.SA    0.200982
9033 2021-12-31  VIVT3.SA    0.200711
3639 2021-12-31  ENBR3.SA    0.184389
2595 2021-12-31  CPLE6.SA    0.173715
1116 2021-12-31  BEEF3.SA    0.170967
8337 2021-12-31  TIMS3.SA    0.166912
6597 2021-12-31  PETR4.SA    0.150632
           Date       cod  retorno_6m
6511 2022-01-31  PETR3.SA    0.519743
6598 2022-01-31  PETR4.SA    0.430887
5989 2022-01-31  MRFG3.SA    0.361242
6859 2022-01-31  PRIO3.SA    0.340056
3640 2022-01-31  ENBR3.SA    0.301167
2596 2022-01-31  CPLE6.SA    0.289427
9034 2022-01-31  VIVT3.SA    0.250335
2509 2022-01-31  CPFE3.SA    0.236610
8338 2022-01-31  TIMS3.SA    0.199406
5206 2022-01-31  JBSS3.SA    0.192814
           Date        cod  retorno_6m
6512 2022-02-28   PETR3.SA    0.458899
6599 2022-02-28   PETR4.SA    0.404717
6860 2022-02-28   PRIO3.SA    0.346896
1118 2022-02-28   BEEF3.SA    0.338437
5990 2022-02-28   MRFG3.SA    0.284814
1031 2022-02-28   BBSE3.SA    0.256798
5207 2022-02-28   JBSS3.SA    0.214813
8078 2022-02-28  SULA11.SA    0.195027
9035 2022-02-28   VIVT3.SA    0.189904
770  2022-02-28   BBAS3.SA    0.186781
           Date        cod  retorno_6m
2163 2022-03-31   CIEL3.SA    0.429947
6513 2022-03-31   PETR3.SA    0.402022
6600 2022-03-31   PETR4.SA    0.379964
8079 2022-03-31  SULA11.SA    0.371081
1032 2022-03-31   BBSE3.SA    0.332060
3642 2022-03-31   ENBR3.SA    0.331774
6165 2022-03-31   MULT3.SA    0.320745
8688 2022-03-31   VALE3.SA    0.302143
9036 2022-03-31   VIVT3.SA    0.301721
2685 2022-03-31   CRFB3.SA    0.293321
           Date       cod  retorno_6m
2164 2022-04-30  CIEL3.SA    0.634669
6514 2022-04-30  PETR3.SA    0.469780
1120 2022-04-30  BEEF3.SA    0.431935
7471 2022-04-30  RRRP3.SA    0.429499
2512 2022-04-30  CPFE3.SA    0.410178
6601 2022-04-30  PETR4.SA    0.370632
6166 2022-04-30  MULT3.SA    0.366539
4774 2022-04-30  HYPE3.SA    0.358838
5296 2022-04-30  JHSF3.SA    0.354038
1816 2022-04-30  BRML3.SA    0.323570
           Date       cod  retorno_6m
2165 2022-05-31  CIEL3.SA    1.001499
7472 2022-05-31  RRRP3.SA    0.765025
1121 2022-05-31  BEEF3.SA    0.700793
5297 2022-05-31  JHSF3.SA    0.544965
6515 2022-05-31  PETR3.SA    0.483148
4775 2022-05-31  HYPE3.SA    0.457410
2513 2022-05-31  CPFE3.SA    0.439206
6602 2022-05-31  PETR4.SA    0.398833
7733 2022-05-31  SBSP3.SA    0.387514
6863 2022-05-31  PRIO3.SA    0.379497
           Date       cod  retorno_6m
2166 2022-06-30  CIEL3.SA    0.657639
3471 2022-06-30  ELET6.SA    0.473311
3384 2022-06-30  ELET3.SA    0.410011
4776 2022-06-30  HYPE3.SA    0.367365
1035 2022-06-30  BBSE3.SA    0.300746
1122 2022-06-30  BEEF3.SA    0.284707
2514 2022-06-30  CPFE3.SA    0.264349
774  2022-06-30  BBAS3.SA    0.206000
6603 2022-06-30  PETR4.SA    0.196841
6516 2022-06-30  PETR3.SA    0.193820
           Date       cod  retorno_6m
2167 2022-07-31  CIEL3.SA    0.941196
3472 2022-07-31  ELET6.SA    0.429527
1123 2022-07-31  BEEF3.SA    0.409166
4777 2022-07-31  HYPE3.SA    0.391161
3385 2022-07-31  ELET3.SA    0.323627
1036 2022-07-31  BBSE3.SA    0.302539
6604 2022-07-31  PETR4.SA    0.286958
427  2022-07-31  ASAI3.SA    0.275232
6517 2022-07-31  PETR3.SA    0.257578
2254 2022-07-31  CMIG4.SA    0.256542
           Date       cod  retorno_6m
2168 2022-08-31  CIEL3.SA    1.191809
6779 2022-08-31  POSI3.SA    0.628773
1124 2022-08-31  BEEF3.SA    0.489248
6518 2022-08-31  PETR3.SA    0.482666
6605 2022-08-31  PETR4.SA    0.463257
3473 2022-08-31  ELET6.SA    0.449686
2255 2022-08-31  CMIG4.SA    0.387557
428  2022-08-31  ASAI3.SA    0.377360
3386 2022-08-31  ELET3.SA    0.352220
4778 2022-08-31  HYPE3.SA    0.306471
           Date       cod  retorno_6m
2169 2022-09-30  CIEL3.SA    0.778306
6780 2022-09-30  POSI3.SA    0.474411
6519 2022-09-30  PETR3.SA    0.361832
6606 2022-09-30  PETR4.SA    0.333796
3474 2022-09-30  ELET6.SA    0.253861
4779 2022-09-30  HYPE3.SA    0.160312
6867 2022-09-30  PRIO3.SA    0.156237
3387 2022-09-30  ELET3.SA    0.153632
2517 2022-09-30  CPFE3.SA    0.149249
3996 2022-09-30  EZTC3.SA    0.145365
           Date       cod  retorno_6m
2170 2022-10-31  CIEL3.SA    0.792302
6781 2022-10-31  POSI3.SA    0.715403
5824 2022-10-31  LWSA3.SA    0.524407
4780 2022-10-31  HYPE3.SA    0.378257
7129 2022-10-31  RAIL3.SA    0.352474
7390 2022-10-31  RENT3.SA    0.351772
7738 2022-10-31  SBSP3.SA    0.349652
9217 2022-10-31  WEGE3.SA    0.349226
6607 2022-10-31  PETR4.SA    0.347285
3997 2022-10-31  EZTC3.SA    0.344894
           Date       cod  retorno_6m
9218 2022-11-30  WEGE3.SA    0.549908
7739 2022-11-30  SBSP3.SA    0.316951
6869 2022-11-30  PRIO3.SA    0.287960
5825 2022-11-30  LWSA3.SA    0.270802
431  2022-11-30  ASAI3.SA    0.265783
2171 2022-11-30  CIEL3.SA    0.245746
6608 2022-11-30  PETR4.SA    0.244830
6521 2022-11-30  PETR3.SA    0.241926
4433 2022-11-30  GOAU4.SA    0.208438
1040 2022-11-30  BBSE3.SA    0.206543
           Date       cod  retorno_6m
6870 2022-12-31  PRIO3.SA    0.692133
6783 2022-12-31  POSI3.SA    0.691892
9219 2022-12-31  WEGE3.SA    0.467672
4434 2022-12-31  GOAU4.SA    0.461373
2172 2022-12-31  CIEL3.SA    0.460469
4347 2022-12-31  GGBR4.SA    0.455337
432  2022-12-31  ASAI3.SA    0.367008
7740 2022-12-31  SBSP3.SA    0.355466
1041 2022-12-31  BBSE3.SA    0.344635
1563 2022-12-31  BRAP4.SA    0.257994
           Date       cod  retorno_6m
6871 2023-02-28  PRIO3.SA    0.661850
2347 2023-02-28  CMIN3.SA    0.577827
5914 2023-02-28  MGLU3.SA    0.476744
1564 2023-02-28  BRAP4.SA    0.388208
9220 2023-02-28  WEGE3.SA    0.387036
3565 2023-02-28  EMBR3.SA    0.382128
2869 2023-02-28  CSNA3.SA    0.374261
8698 2023-02-28  VALE3.SA    0.349564
4435 2023-02-28  GOAU4.SA    0.336886
1042 2023-02-28  BBSE3.SA    0.331474

IndexError: index 85 is out of bounds for axis 0 with size 85

In [15]:
#pegando dados do ibov

ibovespa = pdr.get_data_yahoo('^BVSP', start="2015-12-30", end= "2023-01-31" )['Adj Close']

retornos_ibovespa = ibovespa.resample("M").last().pct_change().dropna()

retornos_ibovespa

[*********************100%***********************]  1 of 1 completed

Date
2016-01-31   -0.067912
2016-02-29    0.059100
2016-03-31    0.169673
2016-04-30    0.077035
2016-05-31   -0.100889
                ...
2022-09-30    0.004693
2022-10-31    0.054527
2022-11-30   -0.030602
2022-12-31   -0.021825
2023-01-31    0.016877
Freq: M, Name: Adj Close, Length: 85, dtype: float64

In [16]:
retornos_modelo['ibovespa'] = retornos_ibovespa.values

retornos_modelo.style.format({
    'retorno': '{:,.2%}'.format,
    'ibovespa': '{:,.2%}'.format
})

NameError: name 'retornos_modelo' is not defined

In [ ]:
qs.extend_pandas()

retornos_modelo['retorno'].plot_monthly_heatmap()

retornos_modelo['ibovespa'].plot_monthly_heatmap()

In [ ]:
serie_long_short = retornos_modelo['retorno'] - retornos_modelo['ibovespa']

serie_long_short.plot_monthly_heatmap()

In [ ]:
#meses batendo o mercado 

retornos_modelo_bateu_mercado = retornos_modelo.copy()

retornos_modelo_bateu_mercado['bateu_mercado'] = retornos_modelo['retorno'] > retornos_modelo['ibovespa']

print(retornos_modelo_bateu_mercado)

proporcao_meses_bateu_o_mercado = sum(retornos_modelo_bateu_mercado['bateu_mercado']/len(retornos_modelo_bateu_mercado['bateu_mercado']))
print(proporcao_meses_bateu_o_mercado)

In [ ]:
#retorno anual

retorno_anual = retornos_modelo.copy()
retorno_anual['retorno'] = retorno_anual['retorno'] + 1 
retorno_anual['ibovespa'] = retorno_anual['ibovespa'] + 1

retorno_anual["ano"] = retorno_anual.index.year

retorno_anual["retorno_acumulado_ano"] = retorno_anual.groupby('ano')['retorno'].cumprod() - 1
retorno_anual["retorno_acumulado_ibov"] = retorno_anual.groupby('ano')['ibovespa'].cumprod() - 1

retorno_anual = retorno_anual.reset_index()

retorno_anual = (retorno_anual.groupby(['ano']).tail(1))[['ano', 'retorno_acumulado_ano', 'retorno_acumulado_ibov']]

retorno_anual.style.format({
    'retorno_acumulado_ano': '{:,.2%}'.format,
    'retorno_acumulado_ibov': '{:,.2%}'.format})

In [ ]:
cumulative_ret_modelo = (retornos_modelo.retorno + 1).cumprod() - 1

cumulative_ret_ibov = (retornos_modelo.ibovespa + 1).cumprod() - 1

df_acumulado = pd.DataFrame(data = {"retorno_acum_modelo": cumulative_ret_modelo, "retorno_acum_ibov" : cumulative_ret_ibov }, index = cumulative_ret_ibov.index)

df_acumulado = df_acumulado.resample("Y").last()

df_acumulado = df_acumulado[['retorno_acum_modelo', 'retorno_acum_ibov']]

df_acumulado.style.format({
    'retorno_acum_modelo': '{:,.2%}'.format,
    'retorno_acum_ibov': '{:,.2%}'.format
})

In [ ]:
df_acumulado.plot()

In [ ]:
selic = sgs.get({'selic': 432}, start = '2016-01-31', end = datetime.now())
inflacao = sgs.get({'ipca': 433, 'igp-m': 189}, start = '2016-01-31', end = datetime.now())

In [ ]:
selic

In [ ]:
inflacao['ipca']

lista_ipca = []
for ipca in inflacao['ipca']:
    lista_ipca.append(ipca)
    
len(lista_ipca)

In [ ]:
retornos_modelo = retornos_modelo[0:-1]

In [ ]:
retornos_modelo['ipca'] = pd.Series(lista_ipca, index = list(retornos_modelo.index))
retornos_modelo['ipca'] = retornos_modelo['ipca']/100

In [ ]:
retornos_modelo['retorno real'] = ((1 + retornos_modelo['retorno'])/(1 + retornos_modelo['ipca'])) - 1
retornos_modelo

In [ ]:
retornos_modelo = retornos_modelo[['retorno','ibovespa','retorno real']]
retornos_modelo
retornos_modelo.style.format({
     'retorno': '{:,.2%}'.format,
     'ibovespa': '{:,.2%}'.format,
     'retorno real': '{:,.2%}'.format
 })

In [ ]:
qs.extend_pandas()

retornos_modelo['retorno'].plot_monthly_heatmap()

retornos_modelo['retorno real'].plot_monthly_heatmap()

retornos_modelo['ibovespa'].plot_monthly_heatmap()

In [ ]:
#retorno anual

retorno_anual = retornos_modelo.copy()
retorno_anual['retorno real'] = retorno_anual['retorno real'] + 1 
retorno_anual['ibovespa'] = retorno_anual['ibovespa'] + 1

retorno_anual["ano"] = retorno_anual.index.year

retorno_anual["retorno_acumulado_ano"] = retorno_anual.groupby('ano')['retorno real'].cumprod() - 1
retorno_anual["retorno_acumulado_ibov"] = retorno_anual.groupby('ano')['ibovespa'].cumprod() - 1

retorno_anual = retorno_anual.reset_index()

retorno_anual = (retorno_anual.groupby(['ano']).tail(1))[['ano', 'retorno_acumulado_ano', 'retorno_acumulado_ibov']]

retorno_anual.style.format({
    'retorno_acumulado_ano': '{:,.2%}'.format,
    'retorno_acumulado_ibov': '{:,.2%}'.format})

In [ ]:
cumulative_ret_modelo = (retornos_modelo.retorno + 1).cumprod() - 1

cumulative_ret_ibov = (retornos_modelo.ibovespa + 1).cumprod() - 1

df_acumulado = pd.DataFrame(data = {"retorno_acum_modelo": cumulative_ret_modelo, "retorno_acum_ibov" : cumulative_ret_ibov }, index = cumulative_ret_ibov.index)

df_acumulado = df_acumulado.resample("Y").last()

df_acumulado = df_acumulado[['retorno_acum_modelo', 'retorno_acum_ibov']]

df_acumulado.style.format({
    'retorno_acum_modelo': '{:,.2%}'.format,
    'retorno_acum_ibov': '{:,.2%}'.format
})

In [ ]:
df_acumulado.plot()